name: Publish

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Get the tag name
        id: get_tag
        run: |
          tag=$(echo ${GITHUB_REF/refs\/tags\//} | cut -c 2-)
          dist_tag=$([[ $tag =~ ^[0-9]+.[0-9]+.[0-9]+$ ]] && echo latest || echo rc)
          echo ::set-output name=DIST_TAG::$dist_tag
        shell: bash
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to npm
        run: |
          npm ci
          npm publish --access public --tag ${{ steps.get_tag.outputs.DIST_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
